# Site settings
title:          Arcadian Group
description:    "The Arcadian Group Story"
baseurl:        "/arcadiangroup"
url:            "https://muitool.github.io"

# Author
author:
  name:         Arcadian Group
  url:          https://arcadiangroup.org
  email:        arcadiangroup@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
